### ISSUE TITLE
LiteSender crash

### ISSUE THREAD

**Issue by KSExtrez** [Eastrall/LiteNetwork#27]
When we send a packet and disconnect a client too fast, we can get a disposed exception, after that the server it's unable to send packets.
## File
`LiteNetwork.Common.Internal.LiteSender.cs`
## Exception type
`System.ObjectDisposedException`
## Steps to reproduce

1. Connect a client to `LiteServer`
2. Disconnect a client and try to send message at the same time
3. Repeat until the LiteSender crash

## Screenshot
![image](https://user-images.githubusercontent.com/45128933/101720996-94aa4d80-3a6c-11eb-81c3-fecf5d9d0c03.png)

**Comment by Eastrall** [comment]
Thanks for reporting this. Do you have more details about the stack trace that could help us identify what disposed object is being used? In your screenshot, it looks like the debugger is broken on line 113 and therefor it's maybe not throwing at this line, but in the next.

A temporary fix would be to wrap the `if !(connectionSocket.SendAsync(socketAsyncEvent))` with a `try...catch` block and call the `OnError()` method when an exception occurs, or just check if the `connectionSocket` is not disposed.

**Comment by KSExtrez** [comment]
Here is the StackTrace
```csharp
at System.Net.Sockets.Socket.ThrowObjectDisposedException()
at System.Net.Sockets.Socket.SendAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.SendAsync(SocketAsyncEventArgs e)
at LiteNetwork.Common.Internal.LiteSender.SendMessage(Socket connectionSocket, Byte[] data) in C:\\Users\\extre\\source\\repos\\LiteNetwork\\src\\LiteNetwork.Common\\Internal\\LiteSender.cs:line 113
at LiteNetwork.Common.Internal.LiteSender.ProcessSendingQueue() in C:\\Users\\extre\\source\\repos\\LiteNetwork\\src\\LiteNetwork.Common\\Internal\\LiteSender.cs:line 93
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```
I think that this issue is caused when we handle a message take a lot of time to process and then we send packet after the client has been disconnected.
This issue  can reproduce more easy with this:

```csharp
public class ClientUser : LiteServerUser
{
    public override Task HandleMessageAsync(ILitePacketStream incomingPacketStream)
    {
        Thread.Sleep(10000); // Disconnect the client before 10s 

        using var welcomePacket = new LitePacket();
        welcomePacket.WriteString("Crash packet"); // Send a packet when the user has been disposed

        return base.HandleMessageAsync(incomingPacketStream);
    }
}
```

Maybe just a `try-catch` on `LiteSender` fix it.

**Comment by Eastrall** [comment]
There is also something wrong in the `LiteSender` process that I've totally missed out and you've just pointed the problem.

> When we send a packet and disconnect a client too fast, we can get a disposed exception, after that the server it's unable to send packets.

In fact, if the socket is disposed, it throws an exception which is totally normal, since we are trying to send a message through a disposed `Socket` object. But, it **shouldn't** crash the `LiteSender`, but it actually **does**. When I was looking around the `LiteSender` I have realized (and this also comes from previous versions), that the `LiteSender` is shared accross **all** connections. Meaning, if you have 500 connections that want to send a packet through their **socket** they will have to wait that other operation are done before sending. 

https://github.com/Eastrall/LiteNetwork/blob/main/src/LiteNetwork.Common/Internal/LiteSender.cs#L45

I believe this isn't correct and just like the `LiteReceiver` in `ReceiveStrategyType.Queued`, each connection **should** have their own `LiteSender` task.

**Comment by KSExtrez** [comment]
Good point, you are right, we should be have something like `LiteReceiver` 😉

**Comment by Eastrall** [comment]
I'm going to work on that issue this weekend and provide a better implementation of the `LiteServerSender` for each connected users.
