### ISSUE TITLE
Send(byte[]) not just sending the bytes?

### ISSUE THREAD

**Issue by Kiina** [Eastrall/LiteNetwork#53]
This might not be a real issue, I might just not understand how exactly to use the library. But since discussions are disabled, I will try it like this.

When creating a connection I need to send a handshake. 

So I've added:

```csharp
protected override void OnConnected()
{
      Console.WriteLine($"New client connected with id: {Id}");
      var initBytes = StringToByteArray("FFFFFFFF");
      Console.WriteLine("Send {0} with length of {1} bytes", ByteArrayToString(initBytes), initBytes.Length); //just to make sure my conversion is correct
      Send(initBytes);
}
```

`FFFFFFFF` is the hex representation of my handshake which I convert into a byte array and use the send method. When opening wireshark, the data of the package looks like this:

`04000000ffffffff` with a length of 8 bytes instead of the expected 4 bytes I got from initBytes.Length.

Where did the `04000000` come from? Does send(byte[]) not send the raw data it's given?

**Comment by Eastrall** [comment]
Hello, thank you for reaching out.
By default, when using the default `LitePacketProcessor`, before sending the "real raw bytes", the processors adds a 4-bytes (`int32`) that represents the length of the actual message.
This is needed in order to apply the message framing algorithm to ensure that the `LiteReceiver` reads the correct amount of bytes.
You can visualize a packet structure like this:
![image](https://user-images.githubusercontent.com/4021025/169874022-6dccc489-bafa-4848-879b-c0aea912db82.png)

As I said above, the first 4-bytes contains the number of bytes that will follow. (Orange)
What follows is actually your real data as a `byte[]`.$

You can find the implementation here:
https://github.com/Eastrall/LiteNetwork/blob/348a9719765b84b6107ba8de90353af937fa1efe/src/LiteNetwork/Internal/LiteSender.cs#L84-L91
As you can see, before sending the packet, we call the `_packetProcessor.AppendHeader()` method that will append the packet header to the raw data. In the case of the built-in packet processor, this will just result in adding the length of the raw packet a prefix:
https://github.com/Eastrall/LiteNetwork/blob/348a9719765b84b6107ba8de90353af937fa1efe/src/LiteNetwork/Protocol/LitePacketProcessor.cs#L81-L91

I hope this explanation helps you.

PS: I apologize for the lack of documentation on this topic. I know this is something really important and **must** be documented. As soon as I have some time, I will add extra documentation on this topic.

Thanks for using `LiteNetwork`!

**Comment by Eastrall** [comment]
You were almost there. The `IncludeHeader` property can be confusing. It actually include the header into the message when its **received**. 
Perhaps this property should be renamed into `IncludeHeaderOnReceive` ? ...

Glad to see that overriding the `AppendHeader()` fixes the issue. Feel free to close the issue if needed. 😄
